name: Publish SSL Images

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  IMAGE_NAME: server-ssl

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platforms::linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64,linux/i386
          echo ::set-output name=docker_username::drakeapps
          echo ::set-output name=version::${GITHUB_REF#refs/*/}
          echo ::set-output name=hash::${GITHUB_SHA}
      - name: Set up buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: GHCR Login
        if: success()
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build rpi image
        if: success() && contains(steps.prepare.outputs.version, 'master')
        run: |
          docker buildx build \
            --output type=image,name=ghcr.io/drakeapps/cloud-led-controller/server-ssl,push=true \
            --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --tag "ghcr.io/drakeapps/cloud-led-controller/server-ssl:latest" \
            --file Dockerfile .